package com.xinyusoft.projectlist.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_BEAN".
 */
public class AppBean {

    private Long id;
    /** Not-null value. */
    private String appName;
    private String author;
    private String localVersion;
    private String firstVersion;
    private String nowVersion;
    private boolean isShow = true;

    public AppBean() {
    }

    public AppBean(Long id) {
        this.id = id;
    }

    public AppBean(Long id, String appName, String author, String localVersion, String firstVersion, String nowVersion) {
        this.id = id;
        this.appName = appName;
        this.author = author;
        this.localVersion = localVersion;
        this.firstVersion = firstVersion;
        this.nowVersion = nowVersion;
    }

    public boolean isShow() {
        return isShow;
    }

    public void setIsShow(boolean isShow) {
        this.isShow = isShow;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAppName() {
        return appName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getLocalVersion() {
        return localVersion;
    }

    public void setLocalVersion(String localVersion) {
        this.localVersion = localVersion;
    }

    public String getFirstVersion() {
        return firstVersion;
    }

    public void setFirstVersion(String firstVersion) {
        this.firstVersion = firstVersion;
    }

    public String getNowVersion() {
        return nowVersion;
    }

    public void setNowVersion(String nowVersion) {
        this.nowVersion = nowVersion;
    }

}
